"""add biography

Revision ID: d13708c2320a
Revises: a88a97787bff
Create Date: 2026-04-17 01:09:37.313492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13708c2320a'
down_revision: Union[str, Sequence[str], None] = 'a88a97787bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chars', sa.Column('biography', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chars', 'biography')
    # ### end Alembic commands ###
